AWSTemplateFormatVersion: '2010-09-09'
Description: |
  SoftwareLabs Remote Toolkit Test stack
Resources:
  CodeArtifactPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - codeartifact:Create*
              - codeartifact:DeleteDomain
              - codeartifact:DeleteRepository
              - codeartifact:Describe*
              - codeartifact:Get*
              - codeartifact:List*
              - codeartifact:TagResource
              - codeartifact:Associate*
            Resource:
              - arn:aws:codeartifact:${region}:${account_id}:domain/aws-orbit*
              - arn:aws:codeartifact:${region}:${account_id}:repository/aws-orbit*
          - Effect: Allow
            Action:
              - codeartifact:GetAuthorizationToken
              - codeartifact:GetRepositoryEndpoint
              - codeartifact:ReadFromRepository
            Resource: '*'
